module: FilestackSDK
author: Filestack
github_url: http://github.com/filestack/filestack-swift

theme: fullwidth
clean: true

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, FilestackSDK.xcodeproj, -target, FilestackSDK]