name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Show Xcode SDKs
      run: xcodebuild -showsdks
    - name: Build
      run: xcodebuild -scheme "FilestackSDK" -destination "platform=iOS Simulator,name=iPhone 12 Pro Max" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean build build-for-testing | xcpretty;
    - name: Run tests
      run: xcodebuild -scheme "FilestackSDK" -destination "platform=iOS Simulator,name=iPhone 12 Pro Max" -configuration Debug test-without-building | xcpretty;
